from PyQt6.QtWidgets import QWidget, QGridLayout, QPushButton, QLabel, QLineEdit

class GenericLineEntryBox(QWidget):

        def __init__(self, window_title, label_string, save_function, save_function_options = [], default_text = None):
            # Requirements for save_function:
            # -Must return a boolean that indicates whether it exited successfully
            # -First argument must be the parent of any windows generated by the save_function
            # -Remaining n-1 arguments must be provided as a list in save_function_options, or empty list if no other options
            # -Last argument must be a string given by the text of the QLineEdit box
            super().__init__()
            self.window_title = window_title
            self.label_string = label_string
            self.save_function = save_function
            self.save_function_options = save_function_options
            self.default_text = default_text

            self.initUI()
        
        def initUI(self):
            entryLavel = QLabel(self.label_string, self)
            entryLineEdit = QLineEdit(self.default_text, self)

            button = QPushButton('Save')
            button.clicked.connect(lambda: self.saveButtonOnClick(entryLineEdit))

            grid = QGridLayout()
            grid.setSpacing(10)

            grid.addWidget(entryLavel, 1, 0)
            grid.addWidget(entryLineEdit, 1, 1)
            grid.addWidget(button, 2, 1)

            self.setLayout(grid)
            self.setWindowTitle(self.window_title)

        def saveButtonOnClick(self, entryLineEdit):
            if self.save_function_options == []:
                 ok = self.save_function(self, entryLineEdit.text())
            else:
                 ok = self.save_function(self, *self.save_function_options, entryLineEdit.text())
            
            if ok:
                 print(ok)
                 self.destroy()
             